name: ci

on:
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.6.0-chrome105-ff104
      options: --user 1001 # ← https://github.com/cypress-io/github-action/issues/446#issuecomment-987015822
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: "e2e tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          start: yarn test:e2e:ci
          wait-on: "http://localhost:4173"
          wait-on-timeout: 120
          browser: chrome
          record: false
